version: '3.3'

services:
  bot:
    build: .
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
    networks:
      - botnet

  redis:
    image: redis
    restart: always
    env_file:
      - .env
    volumes:
      - redis_data:/data
    networks:
      - botnet

volumes:
  redis_data:

networks:
  botnet:
    driver: "bridge"
